from . import mail_message
from . import mail_notification
from . import mail_channel
from . import mail_gateway
from . import ir_websocket
from . import res_partner
from . import mail_guest
from . import mail_gateway_abstract
from . import res_users
from . import mail_thread
