# Copyright 2018 Therp BV <https://therp.nl>
# Copyright 2022 Hunki Enterprises BV <https://hunki-enterprises.com>
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
{
    "name": "Autogenerated headers",
    "version": "17.0.1.0.0",
    "author": "Hunki Enterprises BV, Therp BV,Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/social",
    "license": "AGPL-3",
    "category": "Tools",
    "summary": "Add headers to Odoo's mails indicating they are autogenerated",
    "depends": [
        "mail",
    ],
}
