# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.5.2
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 13.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups:
- mail_restrict_follower_selection
repo_description: Addons concerning Odoo's social features and messaging in general.
repo_name: Social addons for Odoo
repo_slug: social
repo_website: https://github.com/OCA/social
travis_apt_packages: []
travis_apt_sources: []
