name: Enforce .banned.txt
on:
  pull_request:
    types: [opened]
  push:
    paths:
      - .banned.txt
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  enforce_banned18:
    #add github.repository == 'OCA/OpenUpgrade' &&
    if: (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.ref_name == '18.0')
    uses: .github/workflows/ban.yml@18.0
    with:
      base_ref: ${{ github.base_ref || github.ref_name }}
      pr_number: ${{ github.event_name == 'pull_request' && github.event.number || 0 }}
